

steps:

- name: 'gcr.io/cloud-builders/docker'

  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}', '.']



# Push the container image to Container Registry

- name: 'gcr.io/cloud-builders/docker'

  args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}']  



# Deploy container image to Cloud Run

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

  entrypoint: gcloud

  args: 

    - 'run'

    - 'deploy'

    - '${_APP_NAME}'

    - '--image'

    - 'gcr.io/$PROJECT_ID/${_APP_NAME}'

    - '--region'

    - '${_CLOUD_REGION}'

    - --timeout

    - '60m'

    - '--service-account=${_SERVICE_SA}'

    - --cpu

    - '4'

    - --memory

    - '2Gi'

    - '--allow-unauthenticated'