substitutions:
  _APP_NAME: 'capstone-v2'
  _SERVICE_SA: 'sa-capstone@cloud-consulting-sandbox.iam.gserviceaccount.com'
  _CLOUD_REGION: 'europe-west1'


steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}', '.']



# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}']  



# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - '${_APP_NAME}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/${_APP_NAME}'
    - '--region'
    - '${_CLOUD_REGION}'
    - --timeout
    - '60m'
    - '--service-account=${_SERVICE_SA}'
    - --cpu
    - '4'
    - --memory
    - '2Gi'
    - '--allow-unauthenticated'



- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Clean up Container Registry images'
  entrypoint: sh
  args: 
  - '-c'
  - |
    apt-get --yes install jq && \
    gcloud container images list-tags gcr.io/$PROJECT_ID/${_APP_NAME} --format=json \
    | jq 'sort_by(.timestamp.datetime) | reverse | to_entries' \
    | jq '.[] | select(.key > 4) | {digestid : .value.digest} | .digestid' \
    | xargs -I {} gcloud container images delete gcr.io/$PROJECT_ID/${_APP_NAME}@{} --quiet
  


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Clean up Cloud Run revisions'
  entrypoint: sh
  args: 
  - '-c'
  - |
    apt-get --yes install jq && \
    gcloud run revisions list --service ${_APP_NAME} --region ${_CLOUD_REGION} --format=json \
    | jq 'sort_by(.value.metadata.creationTimestamp) | to_entries' \
    | jq '.[] | select(.key > 4) | {name: .value.metadata.name} | .name' \
    | xargs -I {} gcloud run revisions delete {} --region ${_CLOUD_REGION} --quiet
